# -*- coding: utf-8 -*-
"""TrabalhoBigData.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vO7aB4CSmqEnNHMUy9tvU8kaTZuaFFcV

IMPORTAÇÃO DAS DEPENDÊNCIAS
"""

import re
import pandas as pd

from google.colab import drive
drive.mount('/content/drive')

# Você precisa se conectar com o Drive e ter uma pasta
# com o nome ArquivosBigData, contendo nessa pasta o arquivo
# "vendas.txt"

"""OBTENÇÃO DOS DADOS"""

#ABRIR O ARQUIVO DOS DADOS DAS VENDAS NO TXT
dadosVendas = open('/content/drive/MyDrive/ArquivosBigData/vendas.txt', "r").read()

#REGEX PRA PEGAR AS DATAS DAS VENDAS SEPARADAS
regex = r"(Data \d{2}/\d{2}/\d{4}\n(?:.|\n)*?)(?=\nData|$)"
total_vendas = re.findall(regex, dadosVendas)

#Arquivo principal que será manipulado usando o pandas
principal_vendas = open("/content/sample_data/vendas.csv", "w")
principal_vendas.write(f"Data;Hora;Valor\n") #Colunas que serão utilizadas
principal_vendas.close()

for vendas in total_vendas:
   data_regex = r"\b\d{2}/\d{2}/\d{4}\b"
   valores_regex = r"R\$([\d.,]+)"
   hora_regex = r"\d{2}:\d{2}"


   datas = re.search(data_regex, vendas)
   horas = re.findall(hora_regex, vendas)
   valores = re.findall(valores_regex, vendas)

   registrar_vendas = open("/content/sample_data/vendas.csv", "a")

   for i, valor in enumerate(valores):
      registrar_vendas.write(f"{datas.group()};{horas[i]};{valor}\n")

   registrar_vendas.close()

"""ADEQUAÇÃO DOS DADOS"""

df_vendas = pd.read_csv("/content/sample_data/vendas.csv", delimiter=";")

df_vendas["Valor"] = df_vendas["Valor"].apply(lambda x: x.replace(".", ""))
#df_vendas["Valor"] = df_vendas["Valor"].apply(lambda x: x.replace(",", "."))
#é melhor nao substituir a virgula por ponto para passar para o csv e modelar os dados no power bi

#Passa os valores na coluna "Data" para o tipo "datetime" e formata a data com "dt.strftime()" para dia-mes-ano
df_vendas["Data"] = pd.to_datetime(df_vendas["Data"], dayfirst=True)
df_vendas["Data"] = df_vendas["Data"].dt.strftime("%d/%m/%Y") #CONVERTE A COLUNA DATA PARA OBJECT NOVAMENTE... TALVEZ USAR DEPOIS QUE CONVERTER TUDO SEJA MELHOR.

#Passa os valores na coluna "Valor" para o tipo float
#df_vendas["Valor"] = df_vendas["Valor"].astype(float)

print(df_vendas)

#Arquivo gerado para ser usado no PowerBi
df_vendas.to_csv("dados_de_vendas.csv", index=False)